### ISSUE TITLE
[Bug] Error when changing the document after update to 10.5.0

### ISSUE THREAD

**Issue by krieger04** [PDFTron/webviewer-ui#1034]
**WebViewer version**
10.5.0

**The current behavior**
Error when calling "loadDocument" if a document is already displayed beforehand. Error in Browser Console:
TypeError: Ja.reset is not a function
    wa webviewer-core.min.js:14745
    $wa webviewer-core.min.js:14745
    Tfa webviewer-core.min.js:13256
    trigger webviewer-core.min.js:34535
    trigger webviewer-core.min.js:34535
    EN webviewer-core.min.js:13370
    invoke zone.js:372
    run zone.js:134
    x zone.js:1276
    invokeTask zone.js:406
    runTask zone.js:178
    m instrumentation.ts:524
    E zone.js:582

**The expected behavior**
Switching the display to the new document

**Steps to reproduce**

**Comment by krieger04** [comment]
I use a custom RectangleCreateTool. This also does not work after the update. Could this be the problem?

**Comment by bollain** [comment]
Hi @krieger04, 

Can you please submit this issue through our support portal? Please provide:
- Any custom code you are using
- Info on the last version that worked for your code
- Any documents that have issues (if applicable)

https://apryse.com/form/request
